name:                fun-execution
version:             0.1.0.0
description:         Language execution pipeline.
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              https://github.com/Nick-Chapman/fun-execution.git

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- containers
- ansi-terminal
- haskeline
- mtl
- transformers
- EarleyM

default-extensions:
- DuplicateRecordFields
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NondecreasingIndentation
- NumericUnderscores
- RankNTypes
- ScopedTypeVariables

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: src

executables:

  console:
    main:                apps/console.hs
    dependencies:        fun-execution

  batch:
    main:                apps/batch.hs
    dependencies:        fun-execution
